spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${SERVER_PORT:8080}

spring.servlet.multipart.max-file-size=${MAX_UPLOAD_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MAX_UPLOAD_REQUEST_SIZE:12MB}
